In [ ]:
import pandas as pd
import numpy as np
from functools import reduce

In [ ]:
df=pd.read_csv("/content/BL-Flickr-Images-Book (3).csv")
print(df.head())

   Identifier             Edition Statement      Place of Publication  \
0         206                           NaN                    London
1         216                           NaN  London; Virtue & Yorston
2         218                           NaN                    London
3         472                           NaN                    London
4         480  A new edition, revised, etc.                    London

  Date of Publication              Publisher  \
0         1879 [1878]       S. Tinsley & Co.
1                1868           Virtue & Co.
2                1869  Bradbury, Evans & Co.
3                1851          James Darling
4                1857   Wertheim & Macintosh

                                               Title     Author  \
0                  Walter Forbes. [A novel.] By A. A      A. A.
1  All for Greed. [A novel. The dedication signed...  A., A. A.
2  Love the Avenger. By the author of “All for Gr...  A., A. A.
3  Welsh Sketches, chiefly ecclesiastical, to the...  A., E. S.
4  [The World in which I live, and my place in it...  A., E. S.

                                   Contributors  Corporate Author  \
0                               FORBES, Walter.               NaN
1  BLAZE DE BURY, Marie Pauline Rose - Baroness               NaN
2  BLAZE DE BURY, Marie Pauline Rose - Baroness               NaN
3                   Appleyard, Ernest Silvanus.               NaN
4                           BROOME, John Henry.               NaN

   Corporate Contributors Former owner  Engraver Issuance type  \
0                     NaN          NaN       NaN   monographic
1                     NaN          NaN       NaN   monographic
2                     NaN          NaN       NaN   monographic
3                     NaN          NaN       NaN   monographic
4                     NaN          NaN       NaN   monographic

                                          Flickr URL  \
0  http://www.flickr.com/photos/britishlibrary/ta...
1  http://www.flickr.com/photos/britishlibrary/ta...
2  http://www.flickr.com/photos/britishlibrary/ta...
3  http://www.flickr.com/photos/britishlibrary/ta...
4  http://www.flickr.com/photos/britishlibrary/ta...

                            Shelfmarks
0    British Library HMNTS 12641.b.30.
1    British Library HMNTS 12626.cc.2.
2    British Library HMNTS 12625.dd.1.
3  British Library HMNTS 10369.bbb.15.
4     British Library HMNTS 9007.d.28.

In [ ]:
df.shape

(8287, 15)

In [ ]:
type (df)

pandas.core.frame.DataFrame

In [ ]:
for col in df:
      print (col)

Identifier
Edition Statement
Place of Publication
Date of Publication
Publisher
Title
Author
Contributors
Corporate Author
Corporate Contributors
Former owner
Engraver
Issuance type
Flickr URL
Shelfmarks

In [ ]:
to_drop=["Edition Statement",
        'Corporate Author',
        'Corporate Contributors',
        'Former owner',
         'Engraver',
        'Contributors',
        'Issuance type',
        'Shelfmarks']

In [ ]:
df.drop(to_drop,inplace=True,axis=1)
df.head()

,Identifier,Place of Publication,Date of Publication,Publisher,Title,Author,Flickr URL
0,206,London,1879 [1878],S. Tinsley & Co.,Walter Forbes. [A novel.] By A. A,A. A.,http://www.flickr.com/photos/britishlibrary/ta...
1,216,London; Virtue & Yorston,1868,Virtue & Co.,All for Greed. [A novel. The dedication signed...,"A., A. A.",http://www.flickr.com/photos/britishlibrary/ta...
2,218,London,1869,"Bradbury, Evans & Co.",Love the Avenger. By the author of “All for Gr...,"A., A. A.",http://www.flickr.com/photos/britishlibrary/ta...
3,472,London,1851,James Darling,"Welsh Sketches, chiefly ecclesiastical, to the...","A., E. S.",http://www.flickr.com/photos/britishlibrary/ta...
4,480,London,1857,Wertheim & Macintosh,"[The World in which I live, and my place in it...","A., E. S.",http://www.flickr.com/photos/britishlibrary/ta...

In [ ]:
df.set_index('Identifier',inplace=True)
df.head()

,Place of Publication,Date of Publication,Publisher,Title,Author,Flickr URL
Identifier,,,,,,
206,London,1879 [1878],S. Tinsley & Co.,Walter Forbes. [A novel.] By A. A,A. A.,http://www.flickr.com/photos/britishlibrary/ta...
216,London; Virtue & Yorston,1868,Virtue & Co.,All for Greed. [A novel. The dedication signed...,"A., A. A.",http://www.flickr.com/photos/britishlibrary/ta...
218,London,1869,"Bradbury, Evans & Co.",Love the Avenger. By the author of “All for Gr...,"A., A. A.",http://www.flickr.com/photos/britishlibrary/ta...
472,London,1851,James Darling,"Welsh Sketches, chiefly ecclesiastical, to the...","A., E. S.",http://www.flickr.com/photos/britishlibrary/ta...
480,London,1857,Wertheim & Macintosh,"[The World in which I live, and my place in it...","A., E. S.",http://www.flickr.com/photos/britishlibrary/ta...

In [ ]:
df['Date of Publication'].head(25)

Identifier
206            1879 [1878]
216                   1868
218                   1869
472                   1851
480                   1857
481                   1875
519                   1872
667                    NaN
874                   1676
1143                  1679
1280                  1802
1808                  1859
1905                  1888
1929           1839, 38-54
2836                  1897
2854                  1865
2956               1860-63
2957                  1873
3017                  1866
3131                  1899
4598                  1814
4884                  1820
4976                  1800
5382    1847, 48 [1846-48]
5385               [1897?]
Name: Date of Publication, dtype: object

In [ ]:
unwanted_characters = ['[', ',', '-']

def clean_dates(item):
    dop= str(item.loc['Date of Publication'])

    if dop == 'nan' or dop[0] == '[':
        return np.NaN

    for character in unwanted_characters:
        if character in dop:
            character_index = dop.find(character)
            dop = dop[:character_index]

    return dop

df['Date of Publication'] = df.apply(clean_dates, axis = 1)

In [ ]:
df.head(45)

,Place of Publication,Date of Publication,Publisher,Title,Author,Flickr URL
Identifier,,,,,,
206,London,1879,S. Tinsley & Co.,Walter Forbes. [A novel.] By A. A,A. A.,http://www.flickr.com/photos/britishlibrary/ta...
216,London; Virtue & Yorston,1868,Virtue & Co.,All for Greed. [A novel. The dedication signed...,"A., A. A.",http://www.flickr.com/photos/britishlibrary/ta...
218,London,1869,"Bradbury, Evans & Co.",Love the Avenger. By the author of “All for Gr...,"A., A. A.",http://www.flickr.com/photos/britishlibrary/ta...
472,London,1851,James Darling,"Welsh Sketches, chiefly ecclesiastical, to the...","A., E. S.",http://www.flickr.com/photos/britishlibrary/ta...
480,London,1857,Wertheim & Macintosh,"[The World in which I live, and my place in it...","A., E. S.",http://www.flickr.com/photos/britishlibrary/ta...
481,London,1875,William Macintosh,"[The World in which I live, and my place in it...","A., E. S.",http://www.flickr.com/photos/britishlibrary/ta...
519,London,1872,The Author,Lagonells. By the author of Darmayne (F. E. A....,"A., F. E.",http://www.flickr.com/photos/britishlibrary/ta...
667,"pp. 40. G. Bryan & Co: Oxford, 1898",NaN,NaN,"The Coming of Spring, and other poems. By J. A...","A., J.|A., J.",http://www.flickr.com/photos/britishlibrary/ta...
874,London],1676,NaN,"A Warning to the inhabitants of England, and L...",Remaʿ.,http://www.flickr.com/photos/britishlibrary/ta...
1143,London,1679,NaN,A Satyr against Vertue. (A poem: supposed to b...,"A., T.",http://www.flickr.com/photos/britishlibrary/ta...
1280,Coventry,1802,Printed by J. Turner,"An Account of the many and great Loans, Benefa...",NaN,http://www.flickr.com/photos/britishlibrary/ta...
1808,Christiania,1859,NaN,Erindringer som Bidrag til Norges Historie fra...,"AALL, Jacob.",http://www.flickr.com/photos/britishlibrary/ta...
1905,Firenze,1888,NaN,Gli Studi storici in terra d'Otranto ... Framm...,"AAR, Ermanno - pseud. [i.e. Luigi Giuseppe Oro...",http://www.flickr.com/photos/britishlibrary/ta...
1929,Amsterdam,1839,NaN,De Aardbol. Magazijn van hedendaagsche land- e...,NaN,http://www.flickr.com/photos/britishlibrary/ta...
2836,Savona,1897,NaN,Cronache Savonesi dal 1500 al 1570 ... Accresc...,"ABATE, Giovanni Agostino.",http://www.flickr.com/photos/britishlibrary/ta...
2854,London,1865,E. Moxon & Co.,"See-Saw; a novel ... Edited [or rather, writte...","ABATI, Francesco.",http://www.flickr.com/photos/britishlibrary/ta...
2956,Paris,1860,NaN,"Géodésie d'une partie de la Haute Éthiopie,...","ABBADIE, Antoine Thompson d'.",http://www.flickr.com/photos/britishlibrary/ta...
2957,Paris,1873,NaN,[With eleven maps.],"ABBADIE, Antoine Thompson d'.",http://www.flickr.com/photos/britishlibrary/ta...
3017,Puerto-Rico,1866,NaN,"[Historia geográfica, civil y politica de la ...","ABBAD Y LASIERRA, Agustín Íñigo - Bishop of...",http://www.flickr.com/photos/britishlibrary/ta...
3131,New York,1899,W. Abbatt,"The Crisis of the Revolution, being the story ...","ABBATT, William.",http://www.flickr.com/photos/britishlibrary/ta...
4598,Hull,1814,The Author,Peace: a lyric poem. [With prefatory address b...,"ABBOTT, Thomas Eastoe.",http://www.flickr.com/photos/britishlibrary/ta...
4884,London,1820,J. Hatchard & Son,"Abdallah; or, The Arabian Martyr: a Christian ...",NaN,http://www.flickr.com/photos/britishlibrary/ta...
4976,Oxonii,1800,"J. Cooke, etc.",[Abdollatiphi Historiæ Ægypti compendium. [Wit...,NaN,http://www.flickr.com/photos/britishlibrary/ta...
5382,London,1847,Punch Office,The Comic History of England ... With ... colo...,"A'BECKETT, Gilbert Abbott.",http://www.flickr.com/photos/britishlibrary/ta...
5385,London,NaN,"Bradbury, Agnew & Co.",[The comic history of England ... With twenty ...,"A'BECKETT, Gilbert Abbott.",http://www.flickr.com/photos/britishlibrary/ta...
5389,London,NaN,"Bradbury, Agnew & Co.",[The Comic History of Rome ... Illustrated by ...,"A'BECKETT, Gilbert Abbott.",http://www.flickr.com/photos/britishlibrary/ta...
5432,Milano,1893,NaN,Signa: opera in tre atti [founded on the novel...,"A'BECKETT, Gilbert Arthur - and RUDALL (H. A.)",http://www.flickr.com/photos/britishlibrary/ta...
6036,London,1805,C. & R. Baldwin,"The Venetian Outlaw, a drama in three acts ......",NaN,http://www.flickr.com/photos/britishlibrary/ta...
6821,Aberdeen,1837,J. Davidson & Co.,Description of the Coast between Aberdeen and ...,NaN,http://www.flickr.com/photos/britishlibrary/ta...
7521,Wien,1896,NaN,Aus Kaukasischen Ländern. Reisebriefe von H. ...,"ABICH, Wilhelm Hermann.",http://www.flickr.com/photos/britishlibrary/ta...
7630,Abingdon,1898,W. H. Hooke,Selections from the Municipal Chronicles of th...,NaN,http://www.flickr.com/photos/britishlibrary/ta...
8239,Quebec,1899,L. J. Demers & Frère,"The Plains of Abraham, 1759, a spot sacred to ...",NaN,http://www.flickr.com/photos/britishlibrary/ta...
8435,London,1892,Effingham Wilson & Co.,The Witwatersrand Gold Mines. A true and unvar...,"ABRAHAM, Félix - Writer on Mining",http://www.flickr.com/photos/britishlibrary/ta...
8440,London,1894,Effingham Wilson,The New Era of the Goldmining Industry in the ...,"ABRAHAM, Félix - Writer on Mining",http://www.flickr.com/photos/britishlibrary/ta...
11361,Leipzig,NaN,NaN,"Tirol und Vorarlberg ... Mit ... einer Karte, ...","ACHLEITNER, Arthur - and UBL (E.)",http://www.flickr.com/photos/britishlibrary/ta...
11852,"pp. 40. W. Cann: Plymouth, [1876?]",NaN,NaN,"A Question of Holy Writ, suggested by a lectur...","ACKLAND - Lieut., R.N",http://www.flickr.com/photos/britishlibrary/ta...
13074,London,1899,W. Thacker & Co.,A Summer in High Asia: being a record of sport...,"ADAIR, Frederick Edward Shafto.",http://www.flickr.com/photos/britishlibrary/ta...
13364,London,NaN,"Griffith, Farran & Co.",A Hand-book and History of Sidmouth from the T...,NaN,http://www.flickr.com/photos/britishlibrary/ta...
14466,London,NaN,Adams & King,"The Historie of Eald Street, now called Old St...",NaN,http://www.flickr.com/photos/britishlibrary/ta...
14703,1845,1846,NaN,First (-Third) Annual Report on the Geology of...,NaN,http://www.flickr.com/photos/britishlibrary/ta...
15141,London,1893,T. Fisher Unwin,The New Egypt. A social sketch. [Edited by J. ...,"ADAMS, Francis William Lauderdale.",http://www.flickr.com/photos/britishlibrary/ta...
15146,London,1894,T. Fisher Unwin,Tiberius: a drama ... With introduction by W. ...,"ADAMS, Francis William Lauderdale.",http://www.flickr.com/photos/britishlibrary/ta...
16173,enk,1817,"printed by W. Thorne, and published by J. Call...",Memoirs of the Life and Doctrines of the late ...,"ADAMS, Joseph - M.D., F.L.S",http://www.flickr.com/photos/britishlibrary/ta...
16543,London,1816,John Murray,"The Narrative of Robert Adams, a sailor, who w...","Adams, Robert - Sailor",http://www.flickr.com/photos/britishlibrary/ta...
16544,Boston,1817,Wells & Lilley,"[The Narrative of Robert Adams, a sailor, who ...","ADAMS, Robert - Sailor",http://www.flickr.com/photos/britishlibrary/ta...

In [ ]:
def clean_title(title):

    if title == 'nan':
        return 'NaN'

    if title[0] == '[':
        title = title[1: title.find(']')]

    if 'by' in title:
        title = title[:title.find('by')]
    elif 'By' in title:
        title = title[:title.find('By')]

    if '[' in title:
        title = title[:title.find('[')]

    title = title[:-2]


df['Title'] = df['Title'].apply(clean_title)
df.head()

,Place of Publication,Date of Publication,Publisher,Title,Author,Flickr URL
Identifier,,,,,,
206,London,1879,S. Tinsley & Co.,None,A. A.,http://www.flickr.com/photos/britishlibrary/ta...
216,London; Virtue & Yorston,1868,Virtue & Co.,None,"A., A. A.",http://www.flickr.com/photos/britishlibrary/ta...
218,London,1869,"Bradbury, Evans & Co.",None,"A., A. A.",http://www.flickr.com/photos/britishlibrary/ta...
472,London,1851,James Darling,None,"A., E. S.",http://www.flickr.com/photos/britishlibrary/ta...
480,London,1857,Wertheim & Macintosh,None,"A., E. S.",http://www.flickr.com/photos/britishlibrary/ta...